ApplicantBase/applicants/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ApplicantAddView, ApplicantListView, ApplicantsDetailView


urlpatterns = [
    path('', ApplicantListView.as_view(), name='index'),
    path('add/', ApplicantAddView.as_view(), name='ApplicantAdd'),
    path('applicants/', ApplicantListView.as_view(), name='Applicants_list'),
    path('<int:pk>/', ApplicantsDetailView.as_view(), name='DetailView')
]

ApplicantBase/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applicants.urls'))

]

ApplicantBase/applicants/models.py
from django.db import models


# Create your models here.
# Абитуриент, его модель надо будет еще добавить Статус
class Applicant(models.Model):
    STATUS_CHOICES = [

        ('new', 'Новый'),

        ('in_progress', 'В процессе'),

        ('accepted', 'Зачислен'),

        ('rejected', 'Отклонено'),

    ]
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    birth_date = models.DateField()
    contact_phone = models.IntegerField(null=True)
    contact_email = models.EmailField(null=True)
    address = models.TextField(null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['first_name', 'last_name', 'middle_name', 'birth_date'] #Пробуем запретить дубли Физ Лиц



# Модель образовательной программы

class Programm(models.Model):
    name = models.CharField(max_length=255)
    code = models.IntegerField()
    description = models.TextField(default=None)
    budget_seats = models.IntegerField()
    paid_seats = models.IntegerField()


# Модель заявлений

class Applications(models.Model):
    STATUS_CHOICES = [

        ('submitted', 'Подано'),

        ('in_review', 'В рассмотрении'),

        ('accepted', 'Принято'),

        ('rejected', 'Отклонено'),

    ]
    applicant_id = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    programm_id = models.ForeignKey(Programm, on_delete=models.CASCADE)
    submission_date = models.DateField(auto_now=True)  # Дата подачи заявления
    updated_at = models.DateTimeField(auto_now=True)  # Дата обновления
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='submitted')
    # Подумать куда лучше добавить оценки за экзамены


class ExamResult(models.Model):
    applicant_id = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    exam_name = models.CharField(max_length=255)
    score = models.PositiveIntegerField()
    exam_date = models.DateField()

ApplicantBase/applicants/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Applicant


class ApplicantAddView(CreateView):
    model = Applicant

    fields = ['first_name', 'last_name', 'middle_name', 'birth_date',
              'contact_phone', 'contact_email', 'address',]

    template_name = 'applicant_form.html'
    success_url = reverse_lazy('index') #Перенаправление пока на главную, позже понять куда надо


class ApplicantListView(ListView):
    model = Applicant

    template_name = 'applicants_list.html'
    context_object_name = 'applicants'


class ApplicantsDetailView(DetailView):
    model = Applicant

    template_name = 'applicant_detail_view.html'

ApplicantBase/applicants/templates/applicant_detail_view.html
{% extends 'base.html' %}

{% block title %}Карточка {{applicant.first_name }} {{ applicant.last_name }} {% endblock %}

{% block content %}
    <h1>Карточка {{applicant.first_name }} {{ applicant.last_name }}</h1>
    <p>ФИО: {{applicant.first_name }} {{ applicant.last_name }} {{ applicant.middle_name }}</p>

    <a href="{% url 'Applicants_list' %}">Назад к списку</a>
{% endblock %}

ApplicantBase/applicants/templates/applicant_form.html
<!-- Подключаем Flatpickr CSS и JS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% extends 'base.html' %}

{% block title %} Новый Абитуриент {% endblock %}

{% block content %}
<h1>Новый Абитуриент</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<!-- Активируем календарь для поля birth_date -->
<script>
    flatpickr("#id_birth_date", {
        dateFormat: "Y-m-d",  // Формат даты (как в Django)
        allowInput: true,     // Разрешить ручной ввод
    });
</script>
{% endblock %}

ApplicantBase/applicants/templates/applicants_list.html
{% extends 'base.html' %}

{% block title %} All Applicants {% endblock %}

{% block content %}
    <h1>Список всех абитуриентов</h1>
    {% for applicant in applicants %}
        <div class="applicants">
            <h1><a href="{% url 'DetailView' applicant.pk %}">{{ applicant.first_name }} {{ applicant.last_name }} </a></h1>

            
        </div>
    {% endfor %}
{% endblock %}

ApplicantBase/applicants/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Приемная комиссия{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'sidebars.css' %} ">
</head>
<body>
<div class="container">
    <nav>
        <div class="nav-links">
            <a href="{% url 'Applicants_list' %}">Главная</a>
        </div>
        <a href="{% url 'ApplicantAdd' %}" class="btn-primary">Добавить</a>
    </nav>

</div>
{% block content %} {% endblock %}
</body>
</html>

ApplicantBase/applicants/templates/index.html
{% extends 'base.html' %}

{% block title %} All Applicants {% endblock %}

{% block content %}
    <h1>Главная Тут будет контент</h1>
    {% for applicant in applicants %}
        <div class="applicants">
            <h1><a href="{% url 'applicant_detail' applicant.pk">{{ applicant.title }}</a></h1>


        </div>
    {% endfor %}
{% endblock %}